### ISSUE TITLE
Git successful branching

### ISSUE THREAD

**Issue by maciejmiara** [dgnet/Conferia#9]
What do you think about introducing git successful branching?
http://nvie.com/posts/a-successful-git-branching-model/

Or maybe something like Symfony has (there is master and branches named by version number)?

**Comment by cakper** [comment]
As this is a project (like joind in for example) and not a framework/library I'd suggest following general practices used on github (feature branch + PR) and try to avoid burden of multiple version maintenance. 

In this case I don't see benefits of maintaining different version and I'd rather focus on setting up continuous deployment pipeline with feature flags rather than multiple project versions.

**Comment by michalpipa** [comment]
I agree with @cakper. If you want to contribute, just create pull request according to GitHub best practices.

We don't have any release yet, so we don't need any version branches.

**Comment by zibios** [comment]
@michalpipa :+1: the project is for now at too early stage to waste time on version maintenance, continuous deployment is better solution
